---

- name: Create test project | check if already exists
  shell: "oc --config=../kubeconfig get projects"
  register: proj_exists

- name: Create test project | delete if exists
  shell: "oc --config=../kubeconfig delete project {{testproject}}" 
  when: "'{{testproject}}' in proj_exists.stdout"

- name: Create test project | create the test project
  shell: "oc --config=../kubeconfig new-project {{testproject}}"

- name: deploy application | prepare ocpdbtest yaml
  template:
    src: ocpdbtest.yaml
    dest: roles/deploy_test/files/ocpdbtest.yaml

- name: deploy application | prepare ocpdbtest pvc yaml
  template:
    src: ocpdbtestpvc.yaml
    dest: roles/deploy_test/files/ocpdbtestpvc.yaml

- name: deploy application | prepare route yaml
  template:
    src: ocpdbtestroute.yaml
    dest: roles/deploy_test/files/ocpdbtestroute.yaml

- name: deploy application | prepare service yaml
  template:
    src: ocpdbtestsvc.yaml
    dest: roles/deploy_test/files/ocpdbtestsvc.yaml

- name: deploy application | create ocpdbtest pvc
  shell: "oc --config=../kubeconfig create -f roles/deploy_test/files/ocpdbtestpvc.yaml"

- name: deploy application | deploy ocpdbtest deploymentconfig
  shell: "oc --config=../kubeconfig create -f roles/deploy_test/files/ocpdbtest.yaml"

- name: deploy application | create ocpdbtest service
  shell: "oc --config=../kubeconfig create -f roles/deploy_test/files/ocpdbtestsvc.yaml"

- name: deploy application | create route for ocpdbtest
  shell: "oc --config=../kubeconfig create -f roles/deploy_test/files/ocpdbtestroute.yaml"
