apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: ocpdbtest
  name: ocpdbtest
  namespace: {{testproject}}
spec:
  host: ocpdbtest-{{testproject}}.{{ocpappsdomain}}
  to:
    kind: Service
    name: ocpdbtest
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None
