apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{storageclass}}-claim
  namespace: {{testproject}}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
          storage: 1Mi
  storageClassName: {{storageclass}}
