apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  labels:
    app: ocpdbtest
  name: ocpdbtest
  namespace: {{testproject}}
spec:
  replicas: 0
  template:
    metadata:
      labels:
        app: ocpdbtest
    spec:
      containers:
      - name: ocpdbtest
        image: {{localregistry}}       
        env:
        - name: S3_HOST
          value: "{{S3_HOST}}"
        - name: ACCESS_KEY
          value: "{{ACCESS_KEY}}"
        - name: SECRET_KEY
          value: "{{SECRET_KEY}}"
        - name: SSL
          value: "{{SSL}}"
        - name: PSQL_HOST
          value: "{{PSQL_HOST}}"
        - name: PSQL_USER
          value: "{{PSQL_USER}}"
        command: ["httpd-foreground"]
        ports:
        - name: web
          containerPort: 80
        volumeMounts:
        - name: {{storageclass}}-vol1
          mountPath: /var/www/html/
          readOnly: false
        - mountPath: /var/log/ocpdbtest
          name: log
      nodeSelector:
        nodeTest: "true"
      volumes:
      - name: {{storageclass}}-vol1
        persistentVolumeClaim:
          claimName: {{storageclass}}-claim
      - name: log
        emptyDir: {}
  triggers:
  - type: ConfigChange
  strategy:
    type: Rolling
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0
